name: Build, Make and Publish Client

on:
  push:
    branches:
      - develop
      - stage
      - master

  # pull_request:
  #   branches:
  #     - develop
  #     - stage
  #     - master

  workflow_dispatch:

concurrency:
  group: build-and-publish-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '18.x'

jobs:
  make:
    name: Make Electron App
    runs-on: windows-latest
    # environment: ${{ github.ref_name == 'master' && 'production' || github.ref_name == 'stage' && 'staging' || 'development' }}

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Node, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set Yarn timeout
        uses: borales/actions-yarn@v5
        with:
          cmd: config set network-timeout 300000

      - name: Install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: app

      - name: Make Electron App
        uses: borales/actions-yarn@v5
        with:
          cmd: make
          dir: app

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          prerelease: ${{ github.ref_name != 'master' }}

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: 'app/out/make/squirrel.windows/x64/some-ts-electron-app-1.0.0 Setup.exe'
          asset_name: 'some-ts-electron-app-1.0.0 Setup.exe'
          asset_content_type: application/octet-stream

      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create-release.outputs.id }}
      
