name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create-release
        with:
          artifacts: app/src/index.css
          omitBody: true

      - name: Reporter
        shell: bash
        run: |
          echo html_url ${{ steps.create-release.outputs.html_url }}
          echo id ${{ steps.create-release.outputs.id }}
          echo upload_url ${{ steps.create-release.outputs.upload_url }}